### PR TITLE
Dev

### LINKED ISSUE #2: Text 형태 OSS notice 생성
현재 onot이 생성하는 고지문 파일 형태는 html입니다. 
심플한 text 형태로도 고지문을 생성하게 되길 원합니다.

### PR DESCRIPTION
**Pull request by okssum**
text 형태 OSS notic 생성 기능 추가하였습니다.

### CODE REVIEW

**Comment by RobinKumar5986** [comment]
what is the main issue can you please explain because  I am new to this open source contribution and I want to learn how to contribute to in the projects.

**Comment by haksungjang** [comment]
@RobinKumar5986 

It seems that this PR is for https://github.com/sktelecom/onot/issues/2. Although it is written in Korean, but I bet you can read it using translator. :) 

You can refer to the README, https://github.com/sktelecom/onot/blob/main/README.md, for project description and how to contribute. 

Thank you.

**Comment by haksungjang** [comment]
@okssum 
Thank you for your first contribution. I'll merge it to dev branch.

**Review by haksungjang — COMMENTED** [review]
Great!!! :)

**Comment by haksungjang** [comment]
@okssum 

Please make one more PR. Add your name on Contributor section in the README file. 

Thank you.

**Pull request merged**
